// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABt8oyhSNneSZyz0a8kUbdvYSUiRTv0JY',
    appId: '1:1024145575017:web:fe93f157621cece536e6f8',
    messagingSenderId: '1024145575017',
    projectId: 'acrehealth-1dc7f',
    authDomain: 'acrehealth-1dc7f.firebaseapp.com',
    storageBucket: 'acrehealth-1dc7f.appspot.com',
    measurementId: 'G-K8XV806JKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83Y25T9x-7oYohUkIIFPzRii6rJ1xqWE',
    appId: '1:1024145575017:android:72ad2beb325305ed36e6f8',
    messagingSenderId: '1024145575017',
    projectId: 'acrehealth-1dc7f',
    storageBucket: 'acrehealth-1dc7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSiexGXgojxMJMbrmnxwMLyVZ4D0FQigo',
    appId: '1:1024145575017:ios:80955aff4068980d36e6f8',
    messagingSenderId: '1024145575017',
    projectId: 'acrehealth-1dc7f',
    storageBucket: 'acrehealth-1dc7f.appspot.com',
    iosClientId: '1024145575017-0100kfjd2fi3ejau7qnfrlgbldnj37c4.apps.googleusercontent.com',
    iosBundleId: 'com.today.nars',
  );
}
